services:
  db:
    image: mysql:8.0
    container_name: mysql_agendamento
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: teste123
      MYSQL_DATABASE: agendamento_db
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: